# Generated by Django 4.2.1 on 2023-05-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioNutricionista', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
