# Generated by Django 4.2.1 on 2023-05-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioNutricionista', '0003_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
