# Generated by Django 4.2.1 on 2023-05-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioNutricionista', '0004_patient_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imc_records', to='consultorioNutricionista.patient')),
            ],
        ),
    ]
