# Generated by Django 4.2.1 on 2023-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioNutricionista', '0005_imcrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='imc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='IMCRecord',
        ),
    ]
