# Generated by Django 4.2.1 on 2023-05-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioNutricionista', '0006_consultation_imc_delete_imcrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'get_latest_by': 'fecha_consulta'},
        ),
        migrations.AlterField(
            model_name='consultation',
            name='fecha_consulta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
