# Generated by Django 4.2 on 2023-05-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioNutricionista', '0006_consultation_imc_delete_imcrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'get_latest_by': 'fecha_consulta'},
        ),
    ]
