# Generated by Django 4.2.1 on 2023-05-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioNutricionista', '0007_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='fecha_consulta',
            field=models.DateField(auto_now_add=True),
        ),
    ]
