# Generated by Django 4.2.1 on 2023-05-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioNutricionista', '0008_alter_consultation_fecha_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='fecha_consulta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
