# Generated by Django 4.2 on 2023-05-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioNutricionista', '0007_alter_consultation_options'),
        ('consultorioNutricionista', '0009_alter_consultation_fecha_consulta'),
    ]

    operations = [
    ]
